metadata:
  author: FOSSASIA
  projectname: "Susi Server"
  version: development
build:
  theme:
    name: sphinx_fossasia_theme
  logo: images/susi-logo-original.svg
  subproject:
    - url: https://github.com/fossasia/susi_android
    - url: https://github.com/fossasia/chat.susi.ai
    - url: https://github.com/fossasia/susi_tweetbot
    - url: https://github.com/fossasia/susi_fbbot
    - url: https://github.com/fossasia/susi_slackbot
    - url: https://github.com/fossasia/susi_desktop
      source: .
    - url: https://github.com/fossasia/susi_iOS
    - url: https://github.com/fossasia/susi_telegrambot
publish:
  ghpages:
    url: dev.susi.ai
extras:
  swagger:
    url: http://api.susi.ai/docs/swagger.json
    ui: swagger
  javadoc:
    path: 'src/'
