#
# API Server service which will expose the API Server to the rest of the cluster
#
kind: Service
apiVersion: v1
metadata:
  name: susi-server
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: susi-server