apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-data-disk
  namespace: web
  labels:
    name: server-data-disk
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: server-data-disk
    fsType: ext4