#!/bin/bash
#
# start-susi-server

# user mode
#   .../SUSI.AI/bin/
#   .../SUSI.AI/susi_server/
# system mode
#   prefix/bin/
#   prefix/lib/SUSI.AI/susi_server/

DIR="$(dirname "$(readlink -f "$0")")"
PMA="$(readlink -m "$DIR/../susi_server")"
PMB="$(readlink -m "$DIR/../lib/SUSI.AI/susi_server")"
if [ -d "$PMA" ] ; then
    START="$PMA/bin/start.sh"
elif [ -d "$PMB" ] ; then
    START="$PMB/bin/start.sh"
else
    echo "Cannot find SUSI.AI susi_server folder, giving up" >&2
    exit 1
fi
"$START" -I

