#!/bin/bash

# Starting the script
echo "Starting gh-pagesUpdater authored by Abishek V Ashok with love for FOSSASIA"
echo "..."

# Create the new directory to work in, these will get cleaned by Travis so no worries
mkdir work
cd work

# Adding configurations for git
git config --global user.email "travis@travis-ci.org"
git config --global user.name "susi-gh-bot"

# Clone the git repository of meilix project (the gh-pages branch only)
git clone -b gh-pages --single-branch https://susi-gh-bot:$SOURCE_UPDATER@github.com/fossasia/susi_server.git

# Switching branch
git checkout gh-pages

# Copy the needed docs force replace them with the current
cp -rf ../docs ./susi_server
cp -rf ../README.md ./susi_server/index.md

# Adding everything
git add .

# Checking for staged changes
git status --porcelain|grep "M"
# if there are changes
if [ "$?" = 0 ]; then
  git commit --message "Docs file source update for build:$TRAVIS_BUILD_NUMBER | Generated by Travis CI"
  git remote add origin-pages https://susi-gh-bot:$SOURCE_UPDATER@github.com/fossasia/susi_server.git
  git pull --rebase origin-pages gh-pages
  git push --quiet --set-upstream origin-pages gh-pages
  echo "Commit has been made, Happy coding :)"
else
  echo "No changes detected.... Not commiting... Happy coding :)"
fi
